deployment:
  tasks:
    # 1. Definir ruta pública en el hosting
    - export DEPLOYPATH=/home/ibbccou/public_html/

    # 2. Limpiar carpeta pública antes de copiar
    - /bin/rm -rf $DEPLOYPATH/*

    # 3. Copiar SOLO el contenido de /public hacia public_html
    - /bin/cp -R public/. $DEPLOYPATH

    # 4. Crear enlace simbólico para /storage
    - /bin/ln -s /home/ibbccou/repositories/IBBSCation/storage/app/public $DEPLOYPATH/storage
